### ISSUE TITLE
Player 2 don't appear

### ISSUE THREAD

**Issue by Acaree** [Dtotoro27/Watermelon-Squad#5]
1.- Sumary:Al morir en una partida de dos jugadores y volver a empezar, el jugador 2 no aparece
2.- Type: Programacion 
3.- Steps to reproduce: Morir siendo 2 personajes y volver a jugar
4.- Actual result: Cuando alguien muere y en la pantalla de seleccion elegimos dos personajes, solo aparece uno
5.- Expected result: El jugador 2 deberia volver a aparecer
6.- Build: 0.5.5.2

**Comment by DavidTheMaaster** [comment]
changed the position of spawn of the player 2 so now appears on the screen
